linters:
  disable-all: true
  enable:
    - errcheck
    - errorlint
    - wrapcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - bodyclose

linters-settings:
  govet:
    check-shadowing: false

issues:
  exclude-rules:
    - path: version\.go
      linters:
        - deadcode
