linters:
  disable-all: true
  enable:
    - errcheck
    - errorlint
    - wrapcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - bodyclose

linters-settings:
  govet:
    disable-all: true
    enable:
      - shadow
