FROM golang:1.18-bullseye

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux

RUN useradd -u 10001 app
USER app
WORKDIR /test

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN make build
RUN mv /test/bin/session-checker /

CMD ["/session-checker"]
