version: '3'
services:
  checker:
    build: .
    depends_on:
        - redis
    ports:
     - "8080:8080"
    command: /session-checker --redis-server redis:6379
  redis:
    image: redis:latest
    ports:
        - "6379:6379"
    command: redis-server
