name: "Build Container"

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    name: "Build Container"
    runs-on: ubuntu-20.04
    environment: dev

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Prepare"
        id: prep
        run: |
          if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            TAG=test
          else
            TAG=$(echo ${GITHUB_REF} | awk -F '/' '{print $3}')
          fi
          REPO_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
          echo ::set-output name=tag::${TAG}
          echo ::set-output name=repo_name::${REPO_NAME}

      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: "Login"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: "Build and Push"
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ secrets.REGISTRY_USERNAME }}/${{ steps.prep.outputs.repo_name }}:${{ steps.prep.outputs.tag }}
