name: "CI"

on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "main"
    paths-ignore:
      - "README.md"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "README.md"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  go_test:
    name: "Go Test"
    strategy:
      matrix:
        go-version: [1.18]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: "Go Setup"
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Cache"
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: "Lint"
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: "Test build"
        working-directory: ./cmd
        run: go build

      - name: "Go test"
        run: make test-short

  integration_test:
    name: "Integration Test"
    needs: [ go_test ]
    runs-on: ubuntu-22.04

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Integration Test with Redis"
        run: make test
