name: "CI"

on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "main"
    paths-ignore:
      - "README.md"
      - ".devcontainer/**"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "README.md"
      - ".devcontainer/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  go_test:
    name: "Go Test"
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Go Setup"
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: true

      - name: "Prepare"
        id: prep
        run: |
          GOROOT=$(go env GOROOT)
          echo "GOROOT=${GOROOT}" >> $GITHUB_OUTPUT

      - name: "Lint"
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
        env:
          GOROOT: ${{ steps.prep.outputs.GOROOT }}

      - name: "Test build"
        working-directory: ./cmd
        run: go build

      - name: "Go test"
        run: make test-short

  integration_test:
    name: "Integration Test"
    needs: [ go_test ]
    runs-on: ubuntu-22.04

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Integration Test with Redis"
        run: make test
