name: 'Build devcontainer'
on:
  pull_request:
    paths:
      - ".devcontainer/**"
      - ".github/.devcontainer/**"
  push:
    branches:
      - main
    paths:
      - ".devcontainer/**"
      - ".github/.devcontainer/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v3
        with:
          use: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and release devcontainer Multi-Platform
        uses: devcontainers/ci@v0.3
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          imageName: ghcr.io/torumakabe/session-chekcer-devcontainer
          cacheFrom: ghcr.io/torumakabe/session-chekcer-devcontainer
          platform: linux/amd64,linux/arm64
          push: always
          subFolder: .github
