name: Release

on:
  push:
    tags:
    - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04

    steps:
      - name: "Prepare"
        id: prep
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' || ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            TAG=test
          else
            TAG=$(echo ${GITHUB_REF} | awk -F '/' '{print $3}')
          fi
          REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
          echo ::set-output name=repo_owner::${REPO_OWNER}
          echo ::set-output name=tag::${TAG}
          echo ::set-output name=repo_name::${REPO_NAME}

      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Build container for scan"
        working-directory: ./
        run: docker build -t ghcr.io/${{ steps.prep.outputs.repo_name }}:scan-tmp .

      - name: "Scan container"
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ steps.prep.outputs.repo_name }}:scan-tmp'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          trivyignores: '.github/workflows/trivy/.trivyignore'

      - name: "Go Setup"
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true

      - name: "GoReleaser"
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "QEMU Setup"
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: "Docker buildx Setup"
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: "Registry Login"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ steps.prep.outputs.repo_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build & Publish"
        uses: docker/build-push-action@v3
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ steps.prep.outputs.repo_owner }}/${{ steps.prep.outputs.repo_name }}:${{ steps.prep.outputs.tag }}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
