name: "Scan"

on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "main"
    paths-ignore:
      - "README.md"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  scan:
    name: "Scan"
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Prepare"
        id: prep
        run: |
          if [[ ${{ github.event_name }} == 'workflow_dispatch' ]]; then
            TAG=test
          else
            TAG=$(echo ${GITHUB_REF} | awk -F '/' '{print $3}')
          fi
          REPO_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
          echo ::set-output name=tag::${TAG}
          echo ::set-output name=repo_name::${REPO_NAME}

      - name: "Build"
        run: docker build . -t ghcr.io/${{ secrets.REGISTRY_USERNAME }}/${{ steps.prep.outputs.repo_name }}:${{ steps.prep.outputs.tag }}

      - name: "Scan"
        uses: Azure/container-scan@v0
        with:
          image-name: ghcr.io/${{ secrets.REGISTRY_USERNAME }}/${{ steps.prep.outputs.repo_name }}:${{ steps.prep.outputs.tag }}
